CREATE TABLE WEATHER_DATA (
    ID NUMBER PRIMARY KEY,
    DISTRICT VARCHAR2(50),
    TEMPERATURE NUMBER,
    HUMIDITY NUMBER,
    AIR_PRESSURE NUMBER,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
