openapi: 3.0.0
info:
  title: Weather Map API
  description: API for accessing real-time weather data
  version: 1.0.0
paths:
  /weather:
    get:
      summary: Get weather data
      responses:
        '200':
          description: Successful response
